// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/contact.dart';
import 'models/notification.dart';
import 'models/usersettings.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2880320336740233460),
    name: 'Contact',
    lastPropertyId: const obx_int.IdUid(18, 92743786241616720),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7786158392996668689),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6523278049049770428),
        name: 'firstName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 217775021293924972),
        name: 'lastName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6166988337166864792),
        name: 'nickname',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7957976957453740499),
        name: 'frequency',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1772358295599308212),
        name: 'birthday',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2589002527012177649),
        name: 'lastContacted',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5754904356368802256),
        name: 'anniversary',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1328900568728748115),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2501734851380835312),
        name: 'emails',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8612828127895035517),
        name: 'notes',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1318182758170310109),
        name: 'youtubeUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 1553841248143349046),
        name: 'instagramHandle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1723202139627553320),
        name: 'facebookUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 8191253130450763372),
        name: 'snapchatHandle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3238018542597221696),
        name: 'xHandle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 2634893898965425767),
        name: 'linkedInUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 92743786241616720),
        name: 'nextContact',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7591824227650634640),
    name: 'Notification',
    lastPropertyId: const obx_int.IdUid(5, 8056842301395819837),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2526380771482385965),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1447157478650054107),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3848453167690064986),
        name: 'body',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1280843455156809647),
        name: 'payload',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8056842301395819837),
        name: 'scheduledTime',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8348027708397283958),
    name: 'UserSettings',
    lastPropertyId: const obx_int.IdUid(6, 6240070234979785254),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4787548043429071349),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 644703998999399751),
        name: 'remindersEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9132725939087425381),
        name: 'alertsEnabled',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5292993186006166592),
        name: 'notificationHour',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7619820673145648303),
        name: 'notificationMinute',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6240070234979785254),
        name: 'defaultFrequency',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 8348027708397283958),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Contact: obx_int.EntityDefinition<Contact>(
      model: _entities[0],
      toOneRelations: (Contact object) => [],
      toManyRelations: (Contact object) => {},
      getId: (Contact object) => object.id,
      setId: (Contact object, int id) {
        object.id = id;
      },
      objectToFB: (Contact object, fb.Builder fbb) {
        final firstNameOffset = fbb.writeString(object.firstName);
        final lastNameOffset = fbb.writeString(object.lastName);
        final nicknameOffset =
            object.nickname == null ? null : fbb.writeString(object.nickname!);
        final frequencyOffset = fbb.writeString(object.frequency);
        final phoneNumberOffset =
            object.phoneNumber == null
                ? null
                : fbb.writeString(object.phoneNumber!);
        final emailsOffset =
            object.emails == null
                ? null
                : fbb.writeList(
                  object.emails!.map(fbb.writeString).toList(growable: false),
                );
        final notesOffset =
            object.notes == null ? null : fbb.writeString(object.notes!);
        final youtubeUrlOffset =
            object.youtubeUrl == null
                ? null
                : fbb.writeString(object.youtubeUrl!);
        final instagramHandleOffset =
            object.instagramHandle == null
                ? null
                : fbb.writeString(object.instagramHandle!);
        final facebookUrlOffset =
            object.facebookUrl == null
                ? null
                : fbb.writeString(object.facebookUrl!);
        final snapchatHandleOffset =
            object.snapchatHandle == null
                ? null
                : fbb.writeString(object.snapchatHandle!);
        final xHandleOffset =
            object.xHandle == null ? null : fbb.writeString(object.xHandle!);
        final linkedInUrlOffset =
            object.linkedInUrl == null
                ? null
                : fbb.writeString(object.linkedInUrl!);
        fbb.startTable(19);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, firstNameOffset);
        fbb.addOffset(2, lastNameOffset);
        fbb.addOffset(3, nicknameOffset);
        fbb.addOffset(4, frequencyOffset);
        fbb.addInt64(5, object.birthday?.millisecondsSinceEpoch);
        fbb.addInt64(6, object.lastContacted?.millisecondsSinceEpoch);
        fbb.addInt64(7, object.anniversary?.millisecondsSinceEpoch);
        fbb.addOffset(8, phoneNumberOffset);
        fbb.addOffset(9, emailsOffset);
        fbb.addOffset(10, notesOffset);
        fbb.addOffset(11, youtubeUrlOffset);
        fbb.addOffset(12, instagramHandleOffset);
        fbb.addOffset(13, facebookUrlOffset);
        fbb.addOffset(14, snapchatHandleOffset);
        fbb.addOffset(15, xHandleOffset);
        fbb.addOffset(16, linkedInUrlOffset);
        fbb.addInt64(17, object.nextContact?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final birthdayValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          14,
        );
        final lastContactedValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          16,
        );
        final anniversaryValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final nextContactValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          38,
        );
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final firstNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final lastNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final nicknameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final frequencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final birthdayParam =
            birthdayValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(birthdayValue);
        final lastContactedParam =
            lastContactedValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(lastContactedValue);
        final nextContactParam =
            nextContactValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(nextContactValue);
        final anniversaryParam =
            anniversaryValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(anniversaryValue);
        final phoneNumberParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final emailsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final notesParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final youtubeUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final instagramHandleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final facebookUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 30);
        final snapchatHandleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final xHandleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final linkedInUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 36);
        final object = Contact(
          id: idParam,
          firstName: firstNameParam,
          lastName: lastNameParam,
          nickname: nicknameParam,
          frequency: frequencyParam,
          birthday: birthdayParam,
          lastContacted: lastContactedParam,
          nextContact: nextContactParam,
          anniversary: anniversaryParam,
          phoneNumber: phoneNumberParam,
          emails: emailsParam,
          notes: notesParam,
          youtubeUrl: youtubeUrlParam,
          instagramHandle: instagramHandleParam,
          facebookUrl: facebookUrlParam,
          snapchatHandle: snapchatHandleParam,
          xHandle: xHandleParam,
          linkedInUrl: linkedInUrlParam,
        );

        return object;
      },
    ),
    Notification: obx_int.EntityDefinition<Notification>(
      model: _entities[1],
      toOneRelations: (Notification object) => [],
      toManyRelations: (Notification object) => {},
      getId: (Notification object) => object.id,
      setId: (Notification object, int id) {
        object.id = id;
      },
      objectToFB: (Notification object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final bodyOffset = fbb.writeString(object.body);
        final payloadOffset =
            object.payload == null ? null : fbb.writeString(object.payload!);
        fbb.startTable(6);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, bodyOffset);
        fbb.addOffset(3, payloadOffset);
        fbb.addInt64(4, object.scheduledTime?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final scheduledTimeValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          12,
        );
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final bodyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final payloadParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final scheduledTimeParam =
            scheduledTimeValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(scheduledTimeValue);
        final object = Notification(
          id: idParam,
          title: titleParam,
          body: bodyParam,
          payload: payloadParam,
          scheduledTime: scheduledTimeParam,
        );

        return object;
      },
    ),
    UserSettings: obx_int.EntityDefinition<UserSettings>(
      model: _entities[2],
      toOneRelations: (UserSettings object) => [],
      toManyRelations: (UserSettings object) => {},
      getId: (UserSettings object) => object.id,
      setId: (UserSettings object, int id) {
        object.id = id;
      },
      objectToFB: (UserSettings object, fb.Builder fbb) {
        final defaultFrequencyOffset = fbb.writeString(object.defaultFrequency);
        fbb.startTable(7);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addBool(1, object.remindersEnabled);
        fbb.addBool(2, object.alertsEnabled);
        fbb.addInt64(3, object.notificationHour);
        fbb.addInt64(4, object.notificationMinute);
        fbb.addOffset(5, defaultFrequencyOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final remindersEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          6,
          false,
        );
        final alertsEnabledParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final notificationHourParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final notificationMinuteParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final defaultFrequencyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final object = UserSettings(
          id: idParam,
          remindersEnabled: remindersEnabledParam,
          alertsEnabled: alertsEnabledParam,
          notificationHour: notificationHourParam,
          notificationMinute: notificationMinuteParam,
          defaultFrequency: defaultFrequencyParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Contact] entity fields to define ObjectBox queries.
class Contact_ {
  /// See [Contact.id].
  static final id = obx.QueryIntegerProperty<Contact>(
    _entities[0].properties[0],
  );

  /// See [Contact.firstName].
  static final firstName = obx.QueryStringProperty<Contact>(
    _entities[0].properties[1],
  );

  /// See [Contact.lastName].
  static final lastName = obx.QueryStringProperty<Contact>(
    _entities[0].properties[2],
  );

  /// See [Contact.nickname].
  static final nickname = obx.QueryStringProperty<Contact>(
    _entities[0].properties[3],
  );

  /// See [Contact.frequency].
  static final frequency = obx.QueryStringProperty<Contact>(
    _entities[0].properties[4],
  );

  /// See [Contact.birthday].
  static final birthday = obx.QueryDateProperty<Contact>(
    _entities[0].properties[5],
  );

  /// See [Contact.lastContacted].
  static final lastContacted = obx.QueryDateProperty<Contact>(
    _entities[0].properties[6],
  );

  /// See [Contact.anniversary].
  static final anniversary = obx.QueryDateProperty<Contact>(
    _entities[0].properties[7],
  );

  /// See [Contact.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<Contact>(
    _entities[0].properties[8],
  );

  /// See [Contact.emails].
  static final emails = obx.QueryStringVectorProperty<Contact>(
    _entities[0].properties[9],
  );

  /// See [Contact.notes].
  static final notes = obx.QueryStringProperty<Contact>(
    _entities[0].properties[10],
  );

  /// See [Contact.youtubeUrl].
  static final youtubeUrl = obx.QueryStringProperty<Contact>(
    _entities[0].properties[11],
  );

  /// See [Contact.instagramHandle].
  static final instagramHandle = obx.QueryStringProperty<Contact>(
    _entities[0].properties[12],
  );

  /// See [Contact.facebookUrl].
  static final facebookUrl = obx.QueryStringProperty<Contact>(
    _entities[0].properties[13],
  );

  /// See [Contact.snapchatHandle].
  static final snapchatHandle = obx.QueryStringProperty<Contact>(
    _entities[0].properties[14],
  );

  /// See [Contact.xHandle].
  static final xHandle = obx.QueryStringProperty<Contact>(
    _entities[0].properties[15],
  );

  /// See [Contact.linkedInUrl].
  static final linkedInUrl = obx.QueryStringProperty<Contact>(
    _entities[0].properties[16],
  );

  /// See [Contact.nextContact].
  static final nextContact = obx.QueryDateProperty<Contact>(
    _entities[0].properties[17],
  );
}

/// [Notification] entity fields to define ObjectBox queries.
class Notification_ {
  /// See [Notification.id].
  static final id = obx.QueryIntegerProperty<Notification>(
    _entities[1].properties[0],
  );

  /// See [Notification.title].
  static final title = obx.QueryStringProperty<Notification>(
    _entities[1].properties[1],
  );

  /// See [Notification.body].
  static final body = obx.QueryStringProperty<Notification>(
    _entities[1].properties[2],
  );

  /// See [Notification.payload].
  static final payload = obx.QueryStringProperty<Notification>(
    _entities[1].properties[3],
  );

  /// See [Notification.scheduledTime].
  static final scheduledTime = obx.QueryDateProperty<Notification>(
    _entities[1].properties[4],
  );
}

/// [UserSettings] entity fields to define ObjectBox queries.
class UserSettings_ {
  /// See [UserSettings.id].
  static final id = obx.QueryIntegerProperty<UserSettings>(
    _entities[2].properties[0],
  );

  /// See [UserSettings.remindersEnabled].
  static final remindersEnabled = obx.QueryBooleanProperty<UserSettings>(
    _entities[2].properties[1],
  );

  /// See [UserSettings.alertsEnabled].
  static final alertsEnabled = obx.QueryBooleanProperty<UserSettings>(
    _entities[2].properties[2],
  );

  /// See [UserSettings.notificationHour].
  static final notificationHour = obx.QueryIntegerProperty<UserSettings>(
    _entities[2].properties[3],
  );

  /// See [UserSettings.notificationMinute].
  static final notificationMinute = obx.QueryIntegerProperty<UserSettings>(
    _entities[2].properties[4],
  );

  /// See [UserSettings.defaultFrequency].
  static final defaultFrequency = obx.QueryStringProperty<UserSettings>(
    _entities[2].properties[5],
  );
}
